FROM php:8.1-cli

# Базовые системные зависимости и расширения PHP для TCP клиента (минимальная поддерживаемая версия 8.1)
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libzip-dev \
    zip \
    unzip \
    && docker-php-ext-install sockets \
    && rm -rf /var/lib/apt/lists/*

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Рабочая директория
WORKDIR /app

# Предварительная установка зависимостей (используем кеш composer)
COPY composer.json composer.lock* ./
RUN if [ -f composer.lock ]; then composer install --no-interaction --prefer-dist; fi

# Копируем остальной проект
COPY . .

# Команда по умолчанию
CMD ["bash"]

